In [1]:
import os
import warnings
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
from sklearn.model_selection import LeaveOneGroupOut, ParameterGrid
from sklearn.metrics import f1_score, balanced_accuracy_score, recall_score, precision_score, confusion_matrix
from xgboost import XGBClassifier

In [2]:
# Suppress warnings
warnings.filterwarnings('ignore')

# Set random seed for reproducibility
seed = 69
torch.manual_seed(seed)
np.random.seed(seed)

# Define root directory
root = '.'

In [3]:
data = pd.read_csv('./new_dataset/maison-llf-features.CSV', sep=",")

In [4]:
data.head(3)

,participant,timestamp,clinical-timestamp,sis-01,sis-02,sis-03,sis-04,sis-05,sis-06,sis,...,sleep-duration-to-wakeup,sleep-wakeup-count,sleep-heartrate-mean,sleep-heartrate-min,sleep-heartrate-max,step-count,step-ratio,step-mean,step-max,step-max-timestamp
0,1,2022-03-31,2022-04-13,5,5,4,4,5,2,25,...,0.00,3,59,54,74,415,0.5000,34.5833,106,13
1,1,2022-04-01,2022-04-13,5,5,4,4,5,2,25,...,0.00,4,61,56,82,447,0.2917,63.8571,185,8
2,1,2022-04-02,2022-04-13,5,5,4,4,5,2,25,...,0.17,3,59,55,83,533,0.4231,56.1132,170,14

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 84 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   participant                            1008 non-null   int64
 1   timestamp                              1008 non-null   object
 2   clinical-timestamp                     1008 non-null   object
 3   sis-01                                 1008 non-null   int64
 4   sis-02                                 1008 non-null   int64
 5   sis-03                                 1008 non-null   int64
 6   sis-04                                 1008 non-null   int64
 7   sis-05                                 1008 non-null   int64
 8   sis-06                                 1008 non-null   int64
 9   sis                                    1008 non-null   int64
 10  ohs-01                                 1008 non-null   int64
 11  ohs-02                                 1008 non-null   int64
 12  ohs-03                                 1008 non-null   int64
 13  ohs-04                                 1008 non-null   int64
 14  ohs-05                                 1008 non-null   int64
 15  ohs-06                                 1008 non-null   int64
 16  ohs-07                                 1008 non-null   int64
 17  ohs-08                                 1008 non-null   int64
 18  ohs-09                                 1008 non-null   int64
 19  ohs-10                                 1008 non-null   int64
 20  ohs-11                                 1008 non-null   int64
 21  ohs-12                                 1008 non-null   int64
 22  ohs                                    1008 non-null   int64
 23  oks-01                                 1008 non-null   int64
 24  oks-02                                 1008 non-null   int64
 25  oks-03                                 1008 non-null   int64
 26  oks-04                                 1008 non-null   int64
 27  oks-05                                 1008 non-null   int64
 28  oks-06                                 1008 non-null   int64
 29  oks-07                                 1008 non-null   int64
 30  oks-08                                 1008 non-null   int64
 31  oks-09                                 1008 non-null   int64
 32  oks-10                                 1008 non-null   int64
 33  oks-11                                 1008 non-null   int64
 34  oks-12                                 1008 non-null   int64
 35  oks                                    1008 non-null   int64
 36  tug                                    1008 non-null   int64
 37  chairstand                             1008 non-null   int64
 38  acceleration-count                     1008 non-null   int64
 39  acceleration-mean                      1008 non-null   float64
 40  acceleration-std                       1008 non-null   float64
 41  acceleration-sum                       1008 non-null   float64
 42  acceleration-entropy                   1008 non-null   float64
 43  acceleration-kurtosis                  1008 non-null   float64
 44  acceleration-skew                      1008 non-null   float64
 45  acceleration-coefficient-of-variation  1008 non-null   float64
 46  acceleration-minutes-with-data         1008 non-null   int64
 47  acceleration-hours-with-data           1008 non-null   int64
 48  acceleration-movement-events-00to06    1008 non-null   int64
 49  acceleration-movement-events-06to12    1008 non-null   int64
 50  acceleration-movement-events-12to18    1008 non-null   int64
 51  acceleration-movement-events-18to24    1008 non-null   int64
 52  acceleration-movement-events-24h       1008 non-null   int64
 53  acceleration-intradaily-variability    1008 non-null   float64
 54  heartrate-count                        1008 non-null   int64
 55  heartrate-min                          1008 non-null   int64
 56  heartrate-max                          1008 non-null   int64
 57  heartrate-mean                         1008 non-null   float64
 58  heartrate-std                          1008 non-null   float64
 59  heartrate-hours-with-data              1008 non-null   int64
 60  motion-count                           1008 non-null   int64
 61  motion-ratio                           1008 non-null   float64
 62  motion-mean                            1008 non-null   float64
 63  motion-max                             1008 non-null   int64
 64  motion-max-timestamp                   1008 non-null   int64
 65  position-count                         1008 non-null   float64
 66  position-duration                      1008 non-null   float64
 67  position-distance-travelled            1008 non-null   float64
 68  sleep-total                            1008 non-null   float64
 69  sleep-deep                             1008 non-null   float64
 70  sleep-light                            1008 non-null   float64
 71  sleep-rem                              1008 non-null   float64
 72  sleep-snoring                          1008 non-null   float64
 73  sleep-duration-to-sleep                1008 non-null   float64
 74  sleep-duration-to-wakeup               1008 non-null   float64
 75  sleep-wakeup-count                     1008 non-null   int64
 76  sleep-heartrate-mean                   1008 non-null   int64
 77  sleep-heartrate-min                    1008 non-null   int64
 78  sleep-heartrate-max                    1008 non-null   int64
 79  step-count                             1008 non-null   int64
 80  step-ratio                             1008 non-null   float64
 81  step-mean                              1008 non-null   float64
 82  step-max                               1008 non-null   int64
 83  step-max-timestamp                     1008 non-null   int64
dtypes: float64(24), int64(58), object(2)
memory usage: 661.6+ KB

In [6]:
# Convert tensors to pandas DataFrame
df = data[["sis", "ohs", "oks"]]

In [7]:
df.head(3)

   sis  ohs  oks
0   25   25   31
1   25   25   31
2   25   25   31

In [8]:
# Compute quartiles for discretization
siss_q1, siss_q2, siss_q3 = np.percentile(df["sis"], [25, 50, 75])
ohss_q1, ohss_q2, ohss_q3 = np.percentile(df["ohs"], [25, 50, 75])
okss_q1, okss_q2, okss_q3 = np.percentile(df["oks"], [25, 50, 75])

In [9]:
# Define quartile-based bins and labels
quartile_labels = [0, 1, 2, 3]

In [10]:
# Apply discretization
df["SISS_Category_Q"] = pd.cut(df["sis"], bins=[df["sis"].min(), siss_q1, siss_q2, siss_q3, df["sis"].max()],
                               labels=quartile_labels, include_lowest=True).astype(int)
df["OHSS_Category_Q"] = pd.cut(df["ohs"], bins=[df["ohs"].min(), ohss_q1, ohss_q2, ohss_q3, df["ohs"].max()],
                               labels=quartile_labels, include_lowest=True).astype(int)

df["OKSS_Category_Q"] = pd.cut(df["oks"], bins=[df["oks"].min(), okss_q1, okss_q2, okss_q3, df["oks"].max()],
                               labels=quartile_labels, include_lowest=True).astype(int)

In [11]:
# Extract features, target, and patient IDs for LOPO
X = data.iloc[:, -46:] ## pd.DataFrame(samples)
y = df["OHSS_Category_Q"]
groups = data["participant"] ## pd.Series(participants)

In [12]:
#84-39 + 1

In [13]:
#X.info()

In [14]:
# Define classifier and hyperparameter grid
#model = XGBClassifier(use_label_encoder=False, eval_metric="mlogloss")
param_grid = {"max_depth": [3, 5, 7], 
              "n_estimators": [20, 50]}

In [15]:
len(y)

1008

In [16]:
len(X)

1008

In [17]:
len(groups)

1008

In [18]:
# Leave-One-Patient-Out CV (LOPO)
outer_logo = LeaveOneGroupOut()

In [19]:
# Initialize results storage
overall_conf_matrix = np.zeros((4, 4))  # Assuming 4 categories (0, 1, 2, 3)
performance_metrics = []

In [20]:
# Outer LOPO Loop
count=0

for train_idx, test_idx in outer_logo.split(X, y, groups):
    #print(train_idx) index
    count=count+1
    print(count)
    
    #if count == 6 or count == 7:
    #    continue 
    X_train_outer, X_test = X.iloc[train_idx].to_numpy(), X.iloc[test_idx].to_numpy()
    y_train_outer, y_test = y.iloc[train_idx].to_numpy(), y.iloc[test_idx].to_numpy()
    groups_train_outer = groups.iloc[train_idx]
    print(groups_train_outer.unique())
    
    # Inner LOPO for Hyperparameter Optimization
    inner_logo = LeaveOneGroupOut()
    best_model = None
    best_score = -np.inf
    
    for inner_train_idx, inner_val_idx in inner_logo.split(X_train_outer, y_train_outer, groups_train_outer):
        X_train_inner, X_val = X_train_outer[inner_train_idx], X_train_outer[inner_val_idx]
        y_train_inner, y_val = y_train_outer[inner_train_idx], y_train_outer[inner_val_idx]
        groups_train_inner = groups_train_outer.iloc[inner_train_idx]
        print(groups_train_inner.unique())
        
        # Hyperparameter tuning
        for params in ParameterGrid(param_grid):
            params = {k: int(v) if isinstance(v, np.generic) else v for k, v in params.items()}
            model = XGBClassifier(use_label_encoder=False, eval_metric="mlogloss")
            model.set_params(**params)
            model.fit(X_train_inner, y_train_inner)
            y_val_pred = model.predict(X_val)
            score = f1_score(y_val, y_val_pred, average="macro")
            # https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html

            if score > best_score:
                best_score = score
                best_model = model
                best_params = params  # Store the best hyperparameters

    # Train best model on full outer training set
    best_model.fit(X_train_outer, y_train_outer)
    y_pred = best_model.predict(X_test)

    # Compute metrics
    f1 = f1_score(y_test, y_pred, average="macro")
    balanced_acc = balanced_accuracy_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred, average="macro")
    precision = precision_score(y_test, y_pred, average="macro")
    conf_matrix = confusion_matrix(y_test, y_pred, labels=[0, 1, 2, 3])

    # Aggregate confusion matrices
    overall_conf_matrix += conf_matrix

    # Store results
    performance_metrics.append([f1, balanced_acc, recall, precision])

1
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 2  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 2  3  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 2  3  4  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 2  3  4  5  7  8  9 10 11 12 13 14 15 16 17 18]
[ 2  3  4  5  6  8  9 10 11 12 13 14 15 16 17 18]
[ 2  3  4  5  6  7  9 10 11 12 13 14 15 16 17 18]
[ 2  3  4  5  6  7  8 10 11 12 13 14 15 16 17 18]
[ 2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18]
[ 2  3  4  5  6  7  8  9 10 12 13 14 15 16 17 18]
[ 2  3  4  5  6  7  8  9 10 11 13 14 15 16 17 18]
[ 2  3  4  5  6  7  8  9 10 11 12 14 15 16 17 18]
[ 2  3  4  5  6  7  8  9 10 11 12 13 15 16 17 18]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 16 17 18]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 17 18]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 18]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
2
[ 1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  3  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  3  4  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  3  4  5  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  3  4  5  6  8  9 10 11 12 13 14 15 16 17 18]
[ 1  3  4  5  6  7  9 10 11 12 13 14 15 16 17 18]
[ 1  3  4  5  6  7  8 10 11 12 13 14 15 16 17 18]
[ 1  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18]
[ 1  3  4  5  6  7  8  9 10 12 13 14 15 16 17 18]
[ 1  3  4  5  6  7  8  9 10 11 13 14 15 16 17 18]
[ 1  3  4  5  6  7  8  9 10 11 12 14 15 16 17 18]
[ 1  3  4  5  6  7  8  9 10 11 12 13 15 16 17 18]
[ 1  3  4  5  6  7  8  9 10 11 12 13 14 16 17 18]
[ 1  3  4  5  6  7  8  9 10 11 12 13 14 15 17 18]
[ 1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 18]
[ 1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
3
[ 1  2  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 2  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  4  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  4  5  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  4  5  6  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  4  5  6  7  9 10 11 12 13 14 15 16 17 18]
[ 1  2  4  5  6  7  8 10 11 12 13 14 15 16 17 18]
[ 1  2  4  5  6  7  8  9 11 12 13 14 15 16 17 18]
[ 1  2  4  5  6  7  8  9 10 12 13 14 15 16 17 18]
[ 1  2  4  5  6  7  8  9 10 11 13 14 15 16 17 18]
[ 1  2  4  5  6  7  8  9 10 11 12 14 15 16 17 18]
[ 1  2  4  5  6  7  8  9 10 11 12 13 15 16 17 18]
[ 1  2  4  5  6  7  8  9 10 11 12 13 14 16 17 18]
[ 1  2  4  5  6  7  8  9 10 11 12 13 14 15 17 18]
[ 1  2  4  5  6  7  8  9 10 11 12 13 14 15 16 18]
[ 1  2  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
4
[ 1  2  3  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 2  3  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  3  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  5  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  5  6  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  5  6  7  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  5  6  7  8 10 11 12 13 14 15 16 17 18]
[ 1  2  3  5  6  7  8  9 11 12 13 14 15 16 17 18]
[ 1  2  3  5  6  7  8  9 10 12 13 14 15 16 17 18]
[ 1  2  3  5  6  7  8  9 10 11 13 14 15 16 17 18]
[ 1  2  3  5  6  7  8  9 10 11 12 14 15 16 17 18]
[ 1  2  3  5  6  7  8  9 10 11 12 13 15 16 17 18]
[ 1  2  3  5  6  7  8  9 10 11 12 13 14 16 17 18]
[ 1  2  3  5  6  7  8  9 10 11 12 13 14 15 17 18]
[ 1  2  3  5  6  7  8  9 10 11 12 13 14 15 16 18]
[ 1  2  3  5  6  7  8  9 10 11 12 13 14 15 16 17]
5
[ 1  2  3  4  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 2  3  4  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  3  4  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  4  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  6  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  6  7  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  6  7  8 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  6  7  8  9 11 12 13 14 15 16 17 18]
[ 1  2  3  4  6  7  8  9 10 12 13 14 15 16 17 18]
[ 1  2  3  4  6  7  8  9 10 11 13 14 15 16 17 18]
[ 1  2  3  4  6  7  8  9 10 11 12 14 15 16 17 18]
[ 1  2  3  4  6  7  8  9 10 11 12 13 15 16 17 18]
[ 1  2  3  4  6  7  8  9 10 11 12 13 14 16 17 18]
[ 1  2  3  4  6  7  8  9 10 11 12 13 14 15 17 18]
[ 1  2  3  4  6  7  8  9 10 11 12 13 14 15 16 18]
[ 1  2  3  4  6  7  8  9 10 11 12 13 14 15 16 17]
6
[ 1  2  3  4  5  7  8  9 10 11 12 13 14 15 16 17 18]
[ 2  3  4  5  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  3  4  5  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  4  5  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  5  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  7  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  7  8 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  7  8  9 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  7  8  9 10 12 13 14 15 16 17 18]
[ 1  2  3  4  5  7  8  9 10 11 13 14 15 16 17 18]
[ 1  2  3  4  5  7  8  9 10 11 12 14 15 16 17 18]
[ 1  2  3  4  5  7  8  9 10 11 12 13 15 16 17 18]
[ 1  2  3  4  5  7  8  9 10 11 12 13 14 16 17 18]
[ 1  2  3  4  5  7  8  9 10 11 12 13 14 15 17 18]
[ 1  2  3  4  5  7  8  9 10 11 12 13 14 15 16 18]
[ 1  2  3  4  5  7  8  9 10 11 12 13 14 15 16 17]
7
[ 1  2  3  4  5  6  8  9 10 11 12 13 14 15 16 17 18]
[ 2  3  4  5  6  8  9 10 11 12 13 14 15 16 17 18]
[ 1  3  4  5  6  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  4  5  6  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  5  6  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  6  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  8 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  8  9 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  8  9 10 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  8  9 10 11 13 14 15 16 17 18]
[ 1  2  3  4  5  6  8  9 10 11 12 14 15 16 17 18]
[ 1  2  3  4  5  6  8  9 10 11 12 13 15 16 17 18]
[ 1  2  3  4  5  6  8  9 10 11 12 13 14 16 17 18]
[ 1  2  3  4  5  6  8  9 10 11 12 13 14 15 17 18]
[ 1  2  3  4  5  6  8  9 10 11 12 13 14 15 16 18]
[ 1  2  3  4  5  6  8  9 10 11 12 13 14 15 16 17]
8
[ 1  2  3  4  5  6  7  9 10 11 12 13 14 15 16 17 18]
[ 2  3  4  5  6  7  9 10 11 12 13 14 15 16 17 18]
[ 1  3  4  5  6  7  9 10 11 12 13 14 15 16 17 18]
[ 1  2  4  5  6  7  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  5  6  7  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  6  7  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  7  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  9 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  9 10 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  9 10 11 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  9 10 11 12 14 15 16 17 18]
[ 1  2  3  4  5  6  7  9 10 11 12 13 15 16 17 18]
[ 1  2  3  4  5  6  7  9 10 11 12 13 14 16 17 18]
[ 1  2  3  4  5  6  7  9 10 11 12 13 14 15 17 18]
[ 1  2  3  4  5  6  7  9 10 11 12 13 14 15 16 18]
[ 1  2  3  4  5  6  7  9 10 11 12 13 14 15 16 17]
9
[ 1  2  3  4  5  6  7  8 10 11 12 13 14 15 16 17 18]
[ 2  3  4  5  6  7  8 10 11 12 13 14 15 16 17 18]
[ 1  3  4  5  6  7  8 10 11 12 13 14 15 16 17 18]
[ 1  2  4  5  6  7  8 10 11 12 13 14 15 16 17 18]
[ 1  2  3  5  6  7  8 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  6  7  8 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  7  8 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  8 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8 10 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8 10 11 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8 10 11 12 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8 10 11 12 13 15 16 17 18]
[ 1  2  3  4  5  6  7  8 10 11 12 13 14 16 17 18]
[ 1  2  3  4  5  6  7  8 10 11 12 13 14 15 17 18]
[ 1  2  3  4  5  6  7  8 10 11 12 13 14 15 16 18]
[ 1  2  3  4  5  6  7  8 10 11 12 13 14 15 16 17]
10
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18]
[ 2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18]

[ 1  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18]
[ 1  2  4  5  6  7  8  9 11 12 13 14 15 16 17 18]
[ 1  2  3  5  6  7  8  9 11 12 13 14 15 16 17 18]
[ 1  2  3  4  6  7  8  9 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  7  8  9 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  8  9 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  9 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 11 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 11 12 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 11 12 13 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 16 17 18]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 17 18]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 18]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17]
11
[ 1  2  3  4  5  6  7  8  9 10 12 13 14 15 16 17 18]
[ 2  3  4  5  6  7  8  9 10 12 13 14 15 16 17 18]
[ 1  3  4  5  6  7  8  9 10 12 13 14 15 16 17 18]
[ 1  2  4  5  6  7  8  9 10 12 13 14 15 16 17 18]
[ 1  2  3  5  6  7  8  9 10 12 13 14 15 16 17 18]
[ 1  2  3  4  6  7  8  9 10 12 13 14 15 16 17 18]
[ 1  2  3  4  5  7  8  9 10 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  8  9 10 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  9 10 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8 10 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 12 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 12 13 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 12 13 14 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 12 13 14 15 17 18]
[ 1  2  3  4  5  6  7  8  9 10 12 13 14 15 16 18]
[ 1  2  3  4  5  6  7  8  9 10 12 13 14 15 16 17]
12
[ 1  2  3  4  5  6  7  8  9 10 11 13 14 15 16 17 18]
[ 2  3  4  5  6  7  8  9 10 11 13 14 15 16 17 18]
[ 1  3  4  5  6  7  8  9 10 11 13 14 15 16 17 18]
[ 1  2  4  5  6  7  8  9 10 11 13 14 15 16 17 18]
[ 1  2  3  5  6  7  8  9 10 11 13 14 15 16 17 18]
[ 1  2  3  4  6  7  8  9 10 11 13 14 15 16 17 18]
[ 1  2  3  4  5  7  8  9 10 11 13 14 15 16 17 18]
[ 1  2  3  4  5  6  8  9 10 11 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  9 10 11 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8 10 11 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 11 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 13 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 13 14 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 13 14 15 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 13 14 15 16 18]
[ 1  2  3  4  5  6  7  8  9 10 11 13 14 15 16 17]
13
[ 1  2  3  4  5  6  7  8  9 10 11 12 14 15 16 17 18]
[ 2  3  4  5  6  7  8  9 10 11 12 14 15 16 17 18]
[ 1  3  4  5  6  7  8  9 10 11 12 14 15 16 17 18]
[ 1  2  4  5  6  7  8  9 10 11 12 14 15 16 17 18]
[ 1  2  3  5  6  7  8  9 10 11 12 14 15 16 17 18]
[ 1  2  3  4  6  7  8  9 10 11 12 14 15 16 17 18]
[ 1  2  3  4  5  7  8  9 10 11 12 14 15 16 17 18]
[ 1  2  3  4  5  6  8  9 10 11 12 14 15 16 17 18]
[ 1  2  3  4  5  6  7  9 10 11 12 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8 10 11 12 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 11 12 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 12 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 14 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 14 15 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 14 15 16 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 14 15 16 17]
14
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 15 16 17 18]
[ 2  3  4  5  6  7  8  9 10 11 12 13 15 16 17 18]
[ 1  3  4  5  6  7  8  9 10 11 12 13 15 16 17 18]
[ 1  2  4  5  6  7  8  9 10 11 12 13 15 16 17 18]
[ 1  2  3  5  6  7  8  9 10 11 12 13 15 16 17 18]
[ 1  2  3  4  6  7  8  9 10 11 12 13 15 16 17 18]
[ 1  2  3  4  5  7  8  9 10 11 12 13 15 16 17 18]
[ 1  2  3  4  5  6  8  9 10 11 12 13 15 16 17 18]
[ 1  2  3  4  5  6  7  9 10 11 12 13 15 16 17 18]
[ 1  2  3  4  5  6  7  8 10 11 12 13 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 11 12 13 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 12 13 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 13 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 15 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 15 16 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 15 16 17]
15
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 16 17 18]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 16 17 18]
[ 1  3  4  5  6  7  8  9 10 11 12 13 14 16 17 18]
[ 1  2  4  5  6  7  8  9 10 11 12 13 14 16 17 18]
[ 1  2  3  5  6  7  8  9 10 11 12 13 14 16 17 18]
[ 1  2  3  4  6  7  8  9 10 11 12 13 14 16 17 18]
[ 1  2  3  4  5  7  8  9 10 11 12 13 14 16 17 18]
[ 1  2  3  4  5  6  8  9 10 11 12 13 14 16 17 18]
[ 1  2  3  4  5  6  7  9 10 11 12 13 14 16 17 18]
[ 1  2  3  4  5  6  7  8 10 11 12 13 14 16 17 18]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 12 13 14 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 13 14 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 14 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 16 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 16 17]
16
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 17 18]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 17 18]
[ 1  3  4  5  6  7  8  9 10 11 12 13 14 15 17 18]
[ 1  2  4  5  6  7  8  9 10 11 12 13 14 15 17 18]
[ 1  2  3  5  6  7  8  9 10 11 12 13 14 15 17 18]
[ 1  2  3  4  6  7  8  9 10 11 12 13 14 15 17 18]
[ 1  2  3  4  5  7  8  9 10 11 12 13 14 15 17 18]
[ 1  2  3  4  5  6  8  9 10 11 12 13 14 15 17 18]
[ 1  2  3  4  5  6  7  9 10 11 12 13 14 15 17 18]
[ 1  2  3  4  5  6  7  8 10 11 12 13 14 15 17 18]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 17 18]
[ 1  2  3  4  5  6  7  8  9 10 12 13 14 15 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 13 14 15 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 14 15 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 15 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 17]
17
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 18]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 18]
[ 1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 18]
[ 1  2  4  5  6  7  8  9 10 11 12 13 14 15 16 18]
[ 1  2  3  5  6  7  8  9 10 11 12 13 14 15 16 18]
[ 1  2  3  4  6  7  8  9 10 11 12 13 14 15 16 18]
[ 1  2  3  4  5  7  8  9 10 11 12 13 14 15 16 18]
[ 1  2  3  4  5  6  8  9 10 11 12 13 14 15 16 18]
[ 1  2  3  4  5  6  7  9 10 11 12 13 14 15 16 18]
[ 1  2  3  4  5  6  7  8 10 11 12 13 14 15 16 18]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 18]
[ 1  2  3  4  5  6  7  8  9 10 12 13 14 15 16 18]
[ 1  2  3  4  5  6  7  8  9 10 11 13 14 15 16 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 14 15 16 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 15 16 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 16 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
18
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 1  2  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 1  2  3  5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 1  2  3  4  6  7  8  9 10 11 12 13 14 15 16 17]
[ 1  2  3  4  5  7  8  9 10 11 12 13 14 15 16 17]
[ 1  2  3  4  5  6  8  9 10 11 12 13 14 15 16 17]
[ 1  2  3  4  5  6  7  9 10 11 12 13 14 15 16 17]
[ 1  2  3  4  5  6  7  8 10 11 12 13 14 15 16 17]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17]
[ 1  2  3  4  5  6  7  8  9 10 12 13 14 15 16 17]
[ 1  2  3  4  5  6  7  8  9 10 11 13 14 15 16 17]
[ 1  2  3  4  5  6  7  8  9 10 11 12 14 15 16 17]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 15 16 17]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 16 17]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 17]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

In [21]:
overall_conf_matrix

array([[ 11., 154.,   5.,  96.],
       [ 74., 169.,   9., 140.],
       [ 19.,  36.,   1.,  42.],
       [119.,  61.,  16.,  56.]])

In [22]:
# Convert results to DataFrame
performance_df = pd.DataFrame(performance_metrics, columns=["Macro-F1", "Balanced Accuracy", "Macro Recall", "Macro Precision"])

# Save performance metrics and overall confusion matrix
output_path = os.path.join(root, "results/model_performance_ohss.xlsx")
with pd.ExcelWriter(output_path) as writer:
    performance_df.to_excel(writer, sheet_name="All_Folds")

In [23]:
performance_df

    Macro-F1  Balanced Accuracy  Macro Recall  Macro Precision
0   0.075758           0.178571      0.044643         0.250000
1   0.000000           0.000000      0.000000         0.000000
2   0.168889           0.339286      0.113095         0.333333
3   0.025424           0.053571      0.013393         0.250000
4   0.011696           0.017857      0.005952         0.333333
5   0.176056           0.446429      0.223214         0.145349
6   0.148656           0.261905      0.130952         0.172457
7   0.289260           0.392857      0.261905         0.351901
8   0.017241           0.035714      0.008929         0.250000
9   0.153846           0.428571      0.214286         0.120000
10  0.008772           0.017857      0.004464         0.250000
11  0.085366           0.166667      0.125000         0.064815
12  0.062500           0.071429      0.035714         0.250000
13  0.111379           0.261905      0.196429         0.136525
14  0.158537           0.464286      0.116071         0.250000
15  0.489583           0.523810      0.523810         0.629630
16  0.044444           0.071429      0.023810         0.333333
17  0.216667           0.464286      0.309524         0.166667

In [24]:
# Plot overall confusion matrix
plt.figure(figsize=(6, 5))
sns.heatmap(overall_conf_matrix, annot=True, cmap="coolwarm", xticklabels=[0, 1, 2, 3], yticklabels=[0, 1, 2, 3])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Overall Confusion Matrix OHSS")
conf_matrix_path = os.path.join(root, "results/overall_confusion_matrix_ohss.pdf")
plt.savefig(conf_matrix_path, dpi=300, bbox_inches='tight')
plt.close()

print(f"\n✅ Performance metrics saved as: {output_path}")
print(f"✅ Overall Confusion Matrix saved as: {conf_matrix_path}")

✅ Performance metrics saved as: .\results/model_performance_ohss.xlsx
✅ Overall Confusion Matrix saved as: .\results/overall_confusion_matrix_ohss.pdf